version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: yugaantar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tagmahal0
    ports:
      - "5432:5432"